import {
  DrivingSchoolLogo,
  ECmomLogo,
  IMDBLogo,
  PortfolioLogo,
  SnapiaLogo,
  WeatherAppLogo,
} from "../Assets/AssetsList";

export const ProjectList = [
  // {
  //   key: 1,
  //   name: "Digital Sign Project ",
  //   image: DrivingSchoolLogo,
  //   clientDemoLink: "https://omsaimotordrivingschool.in/",
  // },
  {
    key: 1,
    name: "Halal-Ku E-commerce & Recomendation - (Laravel - React)",
    image: ECmomLogo,
    skills: ["React, InertiaJS,Daisy UI, Blockchain, Mysql, Laravel"],
    codeLink: "https://github.com/ladanielha/Halalku-main",
    info: "The e-commerce web app is a feature-rich platform that provides halal food and places. THe application has an admin dashboard for managing products, orders, places and users. The platform also allows users to search for products, view product details and reviews, manage their cart, and track order history.",
    //youtube_url: "https://www.youtube.com/embed/0Fin1PrAnSg",
  },
  // {
  //   key: 4,
  //   name: "Snapia (Social Media)",
  //   image: SnapiaLogo,
  //   skills: ["ReactJS, Tailwind CSS ,NodeJS ,ExpressJS, MongoDB, Socket.IO"],
  //   codeLink: "https://github.com/Saurabh-8585/MERN-Social-Media-Frontend",
  //   demoLink: "https://snapia.vercel.app",
  //   info: "Streamlined photo uploads through Cloudinary, Enhanced messaging capabilities by implementing Socket IO, enabling real-time messaging for improved communication.Empowered users to create accounts, post updates, follow others, and engage with posts through liking and commenting.Integrated cutting-edge features such as real-time chat, seamless login with Google, efficient photo uploads, interactive post interactions, robust password management, and precise location tracking for a comprehensive user experience.Developed a news section for users to read news, providing an additional value-added feature to the platform.",
  // },
  {
    key: 2,
    name: "Personal Portfolio (ReactJS)",
    image: PortfolioLogo,
    skills: ["React,React Router DOM, Twilwind CSS"],
    codeLink: "https://github.com/ladanielha/PortofolioDaniel",
    demoLink: "https://portofolio-daniel-34w0mvzpb-laurentiusdanielhs-projects.vercel.app/",
    info: "I created a personal portfolio website using React JS, HTML, and CSS to showcase my projects, skills,[ and background.] The website serves as a platform for people to learn more about me and my professional accomplishments.My portfolio features information about my education, work experience, and technical skills,[ as well as a section highlighting my completed] projects. Overall, my portfolio serves as a valuable asset in advancing my career and achieving my professional goals.",
  },
  {
    key: 3,
    name: "Auth Role Based (Learn Express and React JS)",
    image: PortfolioLogo,
    skills: ["React,React Router, ExpressJS, JWT, MySQL"],
    codeLink:"https://github.com/ladanielha/rbac_session/tree/master",
    info: "Learn how ExpressJS AUTH Role Based and React JS as Frontend.",
  },
  {
    key: 4,
    name: "Shopping Cart (ReactJS)",
    image: ECmomLogo,
    skills: ["React,React Router,CSS,FakeStore API"],
    codeLink: "https://github.com/ladanielha/Tugas_04_MiniShop",
    demoLink: "https://tugas-04-mini-shop-context.vercel.app/",
    info: "Make A shopiing cart system for implementation and learn how to use react context and reducer ",
  },
  {
    key: 5,
    name: "DSSP(Digital Signature Sign Project)(CI)",
    image: WeatherAppLogo,
    skills: ["PHP, Codeigniter, HTML, CSS, PDF Convert lib"],
    codeLink: "https://github.com/ladanielha/DSSP_Project",
    info: "I developed digital web application that is powered by the ILovePDFAPI. Manager can accept the reprt and sign the report while useing the website applications",
  },
  {
    key: 6,
    name: "JKB Website CMS(CI)",
    image: DrivingSchoolLogo,
    clientDemoLink: "https://github.com/ladanielha/Jkb",
  },
  {
    key: 7,
    name: "Joournalku(CI)",
    image: PortfolioLogo,
    skills: ["PHP, Codeigniter, HTML, CSS"],
    codeLink: "https://github.com/ladanielha/Joournalku.id",
    clientDemoLink: "https://github.com/ladanielha/Joournalku.id",
    info: "Content Management System for Journal and User can comment and Admin CMS ",
  },
];

